# Generated by Django 3.2.9 on 2021-11-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='centers',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Center ID')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('center_name', models.CharField(max_length=50, verbose_name='Center Name')),
                ('no_of_covaxin', models.PositiveSmallIntegerField(null=True, verbose_name='No. of Covaxin left')),
                ('no_of_covishield', models.PositiveSmallIntegerField(null=True, verbose_name='No. of Covishield left')),
                ('no_of_sputnik', models.PositiveSmallIntegerField(null=True, verbose_name='No. of Sputnik V left')),
            ],
        ),
        migrations.CreateModel(
            name='registrants',
            fields=[
                ('registrant_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Registrant ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('aadhar_card_no', models.CharField(max_length=50, unique=True, verbose_name='Aadhar Card No.')),
                ('mobile_no', models.CharField(max_length=50, unique=True, verbose_name='Mobile No.')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('city', models.CharField(choices=[('A', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'))), ('B', (('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'))), ('C', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('D', (('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'))), ('E', (('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5')))], max_length=50, verbose_name='city')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=50, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='statuses',
            fields=[
                ('status_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('first_dose', models.CharField(choices=[('taken', 'taken'), ('not_taken', 'not taken')], max_length=50)),
                ('second_dose', models.CharField(choices=[('taken', 'taken'), ('not_taken', 'not taken')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='time_slots',
            fields=[
                ('slot_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_slots', models.IntegerField()),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.centers')),
                ('slot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.time_slots')),
            ],
        ),
        migrations.CreateModel(
            name='vaccination_status',
            fields=[
                ('registrant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='Registration.registrants', verbose_name='Registrant ID')),
                ('vaccine_name', models.CharField(choices=[('covaxin', 'Covaxin'), ('covishield', 'Covishield'), ('sputnik', 'Sputnik V')], max_length=50, verbose_name='Vaccine')),
                ('date_of_1st_dose', models.DateField(null=True, verbose_name='Date of 1st Dose')),
                ('date_of_2nd_dose', models.DateField(null=True, verbose_name='Date of 2nd Dose')),
                ('center_id_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.centers')),
                ('center_id_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.centers')),
                ('vaccination_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.statuses')),
            ],
        ),
    ]
