# Generated by Django 3.2.9 on 2021-11-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination_status',
            old_name='center_id_2',
            new_name='center_2',
        ),
        migrations.RenameField(
            model_name='vaccination_status',
            old_name='registrant_id',
            new_name='registrant',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vaccination_status',
            name='center_id_1',
        ),
        migrations.AddField(
            model_name='vaccination_status',
            name='center_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.centers'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='Registration.centers'),
        ),
    ]
