# Generated by Django 3.2.9 on 2021-11-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20211107_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='center_id',
            new_name='center',
        ),
    ]
