# Generated by Django 3.2.9 on 2021-11-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_delete_vaccination_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='time_slots',
        ),
    ]
