# Generated by Django 3.2.9 on 2021-11-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_delete_statuses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='centers',
        ),
    ]
