# Generated by Django 3.2.9 on 2021-11-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0012_auto_20211110_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrants',
            name='age',
        ),
        migrations.AlterField(
            model_name='registrants',
            name='city',
            field=models.CharField(choices=[('A', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'))), ('B', (('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'))), ('C', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')))], max_length=50, verbose_name='city'),
        ),
    ]
