# Generated by Django 3.2.9 on 2021-11-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0013_auto_20211110_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='Registration.centers'),
        ),
    ]
