# Generated by Django 3.2.9 on 2021-11-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0014_alter_vacancies_center'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vacancies',
        ),
    ]
