# Generated by Django 3.2.9 on 2021-11-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0015_delete_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacancies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empty_slots', models.IntegerField()),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.centers')),
                ('slot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.time_slots')),
            ],
        ),
    ]
