# Generated by Django 3.2.9 on 2021-11-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0016_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.centers'),
        ),
    ]
