# Generated by Django 3.2.9 on 2021-11-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0017_alter_vacancies_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination_status',
            name='vaccine_name',
            field=models.CharField(choices=[('Covaxin', 'Covaxin'), ('Covishield', 'Covishield'), ('Sputnik V', 'Sputnik V')], max_length=50, verbose_name='Vaccine'),
        ),
    ]
