# Generated by Django 3.2.9 on 2021-11-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0019_alter_vaccination_status_center_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination_status',
            name='center_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_1', to='Registration.centers'),
        ),
        migrations.AlterField(
            model_name='vaccination_status',
            name='center_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_2', to='Registration.centers'),
        ),
    ]
