# Generated by Django 3.2.9 on 2021-11-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0021_alter_vaccination_status_registrant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination_status',
            name='center_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_2', to='Registration.centers'),
        ),
    ]
