# Generated by Django 3.2.9 on 2021-11-14 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0022_alter_vaccination_status_center_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='no_of_covaxin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Covaxin left'),
        ),
        migrations.AlterField(
            model_name='centers',
            name='no_of_covishield',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Covishield left'),
        ),
        migrations.AlterField(
            model_name='centers',
            name='no_of_sputnik',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of Sputnik V left'),
        ),
        migrations.AlterField(
            model_name='vaccination_status',
            name='center_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.centers'),
        ),
        migrations.AlterField(
            model_name='vaccination_status',
            name='center_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.centers'),
        ),
        migrations.AlterField(
            model_name='vaccination_status',
            name='date_of_1st_dose',
            field=models.DateField(blank=True, null=True, verbose_name='Date of 1st Dose'),
        ),
        migrations.AlterField(
            model_name='vaccination_status',
            name='date_of_2nd_dose',
            field=models.DateField(blank=True, null=True, verbose_name='Date of 2nd Dose'),
        ),
        migrations.AlterField(
            model_name='vaccination_status',
            name='registrant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='Registration.registrants', verbose_name='Registrant ID'),
        ),
    ]
