# Generated by Django 3.2.9 on 2021-11-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0023_auto_20211114_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuses',
            name='first_dose',
        ),
        migrations.RemoveField(
            model_name='statuses',
            name='second_dose',
        ),
        migrations.AddField(
            model_name='statuses',
            name='first_slot',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='statuses',
            name='second_slot',
            field=models.CharField(default='', max_length=50),
        ),
    ]
