# Generated by Django 3.2.9 on 2021-11-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0024_auto_20211114_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination_status',
            old_name='vaccination_status',
            new_name='booking_status',
        ),
    ]
